### ISSUE TITLE
Binary encoding/decoding

### ISSUE THREAD

**Issue by MonoidMusician** [MonoidMusician/dhall-purescript#6]
Hopefully this is possible in a sane manner :)

For inspiration: https://github.com/paroga/cbor-js/blob/master/cbor.js

**Comment by chexxor** [comment]
It seems like the purpose/utility of Dhall compiler using a binary codec is for the compiler/normalizer to optimize the rehydration of a cached imported Dhall expression.
So, I think this optimization isn't a high priority feature, but that shouldn't stop someone from working on it if they want to. :)

**Comment by MonoidMusician** [comment]
Status update: this is 90% done, but we're having problems with the encoding/decoding of numeric types, since JS does not distinguish them at all. It might require patching that library or creating a new (PS) one.

**Comment by MonoidMusician** [comment]
Fixed in https://github.com/MonoidMusician/dhall-purescript/commit/c9e601479b50ab719cb41eb62067eaeca625c220 and https://github.com/MonoidMusician/dhall-purescript/commit/444a0d350c2e79f68af4a62ef90a811aa88117c2
